environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jetstack
  url: https://charts.jetstack.io
releases:
- chart: jx3/acme
  name: tls-jx-'{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}' 
  values:
  - issuer:
      cluster: true
- chart: '../charts/{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - jx-values.yaml
  - imagePullSecrets.yaml
  - values.yaml.gotmpl
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
    - secret
    - copy
    - --create-namespace
    - --selector
    - "secret.jenkins-x.io/replica-source=true"
    - --to
    - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
